# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  CI:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup do NodeJS
      uses: actions/setup-node@v4.0.0
      with:
        node-version: 16.13.2

    - name: instalação do Mocha e dos pacotes para test
      run:
          cd conversao-temperatura-2-main;
          cd src;
          npm install -g mocha;
          npm install;
          
